#! /bin/bash
# Deploy Configs
cp /var/software/fivem/fivem-server-default/configs/esx_accessories/config.lua [esx]/esx_accessories/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_advanced_holdup/config.lua [esx]/esx_advanced_holdup/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_advancedfishing/config.lua [esx]/esx_advancedfishing/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_advancedgarage/config.lua [esx]/esx_advancedgarage/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_aiomenu/config.lua [esx]/esx_aiomenu/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_aircargojob/config.lua [esx]/esx_aircargojob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_aircraftshop/config.lua [esx]/esx_aircraftshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_airlines/config.lua [esx]/esx_airlines/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_ambulancejob/config.lua [esx]/esx_ambulancejob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_animations/config.lua [esx]/esx_animations/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_armyjob/config.lua [esx]/esx_armyjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_atm/config.lua [esx]/esx_atm/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_bankerjob/config.lua [esx]/esx_bankerjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_barbershop/config.lua [esx]/esx_barbershop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_billing/config.lua [esx]/esx_billing/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_boatshop/config.lua [esx]/esx_boatshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_burglary/config.lua [esx]/esx_burglary/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_carthief/config.lua [esx]/esx_carthief/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_carwash/config.lua [esx]/esx_carwash/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_clotheshop/config.lua [esx]/esx_clotheshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_cruisecontrol/config.lua [esx]/esx_cruisecontrol/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_dmvschool/config.lua [esx]/esx_dmvschool/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_dockshop/config.lua [esx]/esx_dockshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_drugeffects/config.lua [esx]/esx_drugeffects/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_drugs/config.lua [esx]/esx_drugs/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_duty/config.lua [esx]/esx_duty/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_eden_garage/config.lua [esx]/esx_eden_garage/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_fbijob/config.lua [esx]/esx_fbijob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_firejob/config.lua [esx]/esx_firejob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_garage/config.lua [esx]/esx_garage/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_hitmanjob/config.lua [esx]/esx_hitmanjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_holdup/config.lua [esx]/esx_holdup/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_holdupbank/config.lua [esx]/esx_holdupbank/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_hospital/config.lua [esx]/esx_hospital/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_inventoryhud/config.lua [esx]/esx_inventoryhud/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_jb_eden_garage2/config.lua [esx]/esx_jb_eden_garage2/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_joblisting/config.lua [esx]/esx_joblisting/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_jobs/config.lua [esx]/esx_jobs/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_ktackle/config.lua [esx]/esx_ktackle/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_licenseshop/config.lua [esx]/esx_licenseshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_lscustom/config.lua [esx]/esx_lscustom/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_mafiajob/config.lua [esx]/esx_mafiajob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_masks/config.lua [esx]/esx_masks/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_mechanicjob/config.lua [esx]/esx_mechanicjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_moneywash/config.lua [esx]/esx_moneywash/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_nightclubjob/config.lua [esx]/esx_nightclubjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_optionalneeds/config.lua [esx]/esx_optionalneeds/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_phone/config.lua [esx]/esx_phone/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_planting/config.lua [esx]/esx_planting/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_plasticsurgery/config.lua [esx]/esx_plasticsurgery/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_policejob/config.lua [esx]/esx_policejob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_property/config.lua [esx]/esx_property/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_realestateagentjob/config.lua [esx]/esx_realestateagentjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_repairkit/config.lua [esx]/esx_repairkit/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_shops/config.lua [esx]/esx_shops/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_skin/config.lua [esx]/esx_skin/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_society/config.lua [esx]/esx_society/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_status/config.lua [esx]/esx_status/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_taxijob/config.lua [esx]/esx_taxijob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_thelostmcjob/config.lua [esx]/esx_thelostmcjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_thief/config.lua [esx]/esx_thief/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_truckshop/config.lua [esx]/esx_truckshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_unicornjob/config.lua [esx]/esx_unicornjob/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_vehicleshop/config.lua [esx]/esx_vehicleshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_voice/config.lua [esx]/esx_voice/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_weaponshop/config.lua [esx]/esx_weaponshop/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_whitelist/config.lua [esx]/esx_whitelist/config.lua
cp /var/software/fivem/fivem-server-default/configs/esx_whitelistEnhanced/config.lua [esx]/esx_whitelistEnhanced/config.lua
cp /var/software/fivem/fivem-server-default/configs/cv_control/gui.lua [mods]/cv_control/gui.lua
cp /var/software/fivem/fivem-server-default/configs/eden_accessories/config.lua [mods]/eden_accessories/config.lua
cp /var/software/fivem/fivem-server-default/configs/eden_animal/config.lua [mods]/eden_animal/config.lua
cp /var/software/fivem/fivem-server-default/configs/FRFuel/config.lua [mods]/FRFuel/config.lua
cp /var/software/fivem/fivem-server-default/configs/LegacyFuel/config.lua [mods]/LegacyFuel/config.lua
cp /var/software/fivem/fivem-server-default/configs/Peds/config.lua [mods]/Peds/config.lua
cp /var/software/fivem/fivem-server-default/configs/radargun/config.lua [mods]/radargun/config.lua
cp /var/software/fivem/fivem-server-default/configs/skinchanger/config.lua [mods]/skinchanger/config.lua
cp /var/software/fivem/fivem-server-default/configs/StreetRaces/config.lua [mods]/StreetRaces/config.lua
cp /var/software/fivem/fivem-server-default/configs/RealisticVehicleFailure/config.lua [mods]/RealisticVehicleFailure/config.lua
cp /var/software/fivem/fivem-server-default/configs/es_extended/config.lua [essential]/es_extended/config.lua
cp /var/software/fivem/fivem-server-default/configs/essentialmode/config.lua essentialmode/config.lua
